#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <stdio.h>
#include <unistd.h>

int main()
{
    int value;
    int fd;
    //Open File
    openat(fd, "/dev/randomNumber", O_RDONLY);

    if (fd == -1)//open fail
    {
        printf("Failed to open character device file!");
        return -1;
    }

    //Read File, assign value of file to value variable
    read(fd, &value, sizeof(value));
    
    printf("Random 4-byte integer generated by character device : %d\n", value);
    //Close file
    close(fd);
    return 0;
}